---
- name: Configure servers based on AWS tags
  hosts: all:!ec2-44-222-173-228.compute-1.amazonaws.com
  gather_facts: true
  become: true

  tasks:
    - name: Run hostname configuration
      include_tasks: tasks/hostname.yml

    - name: Run package installation
      include_tasks: tasks/install_service.yml

    - name: Run restart schedule configuration
      include_tasks: tasks/restart_cron.yml
