---
- name: Parse restart tag and setup cron
  block:
    - name: Set cron time variables based on tag
      set_fact:
        cron_weekday: "{{ {'Sunday': '0', 'Monday': '1', 'Tuesday': '2', 'Wednesday': '3', 'Thursday': '4', 'Friday': '5', 'Saturday': '6'}[tags.Restart.split()[0]] }}"
        cron_hour: "{{ '0' if 'midnight' in tags.Restart | lower else ('12' if 'noon' in tags.Restart | lower else (tags.Restart.split()[-2].split(':')[0] | int + (12 if 'pm' in tags.Restart | lower and tags.Restart.split()[-2].split(':')[0] | int < 12 else 0))) }}"
        cron_minute: "{{ '0' if 'midnight' in tags.Restart | lower or 'noon' in tags.Restart | lower else tags.Restart.split()[-2].split(':')[1] }}"

    - name: Calculate exact next target datetime
      set_fact:
        target_datetime: "{{
          ansible_facts.date_time.epoch | int
          + (
            ((cron_weekday | int - ansible_facts.date_time.weekday | int) % 7)
            + (7 if ((cron_weekday | int == ansible_facts.date_time.weekday | int) and ((cron_hour | int * 3600 + cron_minute | int * 60) <= (ansible_facts.date_time.hour | int * 3600 + ansible_facts.date_time.minute | int * 60 + ansible_facts.date_time.second | int))) else 0)
            + (7 if (cron_weekday | int - ansible_facts.date_time.weekday | int) < 0 else 0)
          ) * 86400
          - (ansible_facts.date_time.hour | int * 3600 + ansible_facts.date_time.minute | int * 60 + ansible_facts.date_time.second | int)
          + (cron_hour | int * 3600)
          + (cron_minute | int * 60)
        }}"

    - name: Print scheduled restart information with exact date
      ansible.builtin.debug:
        msg: >-
          Server restart has been scheduled based on tag '{{ tags.Restart }}'.
          The exact calculated target time for the restart is:
          {{ lookup('pipe', 'date -d @' + target_datetime | string + ' "+%Y-%m-%d %H:%M:%S"') }}

    - name: Setup scheduled restart using crontab
      ansible.builtin.cron:
        name: "Scheduled server restart"
        minute: "{{ cron_minute }}"
        hour: "{{ cron_hour }}"
        weekday: "{{ cron_weekday }}"
        job: "/sbin/shutdown -r now"
  when:
    - tags is defined
    - tags.Owner is defined
    - tags.Owner == "Nitzan Nathan"
    - tags.Restart is defined
    - tags.Restart | length > 0
